### ISSUE TITLE
git-exporter:  SSL certificate problem: self signed certificate

### ISSUE THREAD

**Issue by Wolvverine** [Poeschl/Hassio-Addons#305] opened 2022-03-17 19:02 UTC
git exporter
 fatal: unable to access 'https://xxx.xxx.xxx.xxx/HomeAssistant_Config.git': SSL certificate problem: self signed certificate
Problem when repository server have self signed certificate

Need an option to disable certificate checking.

**Comment by Poeschl** [comment] 2022-03-17 19:04
Will look into it, but first: This is not a bug, and there are issue templates. They should be used.

**Comment by Wolvverine** [comment] 2022-09-27 19:22
Hello.
@Poeschl 
Is there any nailed down date when it will be possible to use a local repository with self-signed?

**Comment by Poeschl** [comment] 2022-09-27 20:39
It will be done when its done. Busy in RL and no Prio for me. Feel free to contribute.

**Comment by Wolvverine** [comment] 2022-09-27 21:35
@Poeschl 
You have in the pull request.

**Comment by Poeschl** [comment] 2022-11-05 12:23
MR merged

**Closed by Poeschl** 2022-11-05 12:23 UTC
Labels: enhancement, git-exporter
