### ISSUE TITLE
MPD: Error on load tts: Wrong tts file format!, but the sound is still played on speakers

### ISSUE THREAD

**Issue by AdmiralStipe** [Poeschl/Hassio-Addons#295] opened 2022-01-13 15:06 UTC
**Which addon?**
MPD

**Describe the bug**
While everything seems to work OK, I always get same four lines of error in HA log whenever executing any TTS command. The error is: 
"2022-01-13 15:45:00 ERROR (MainThread) [homeassistant.components.tts] Error on load tts: Wrong tts file format!
2022-01-13 15:45:00 ERROR (MainThread) [homeassistant.components.tts] Error on load tts: Wrong tts file format!
2022-01-13 15:45:00 ERROR (MainThread) [homeassistant.components.tts] Error on load tts: Wrong tts file format!
2022-01-13 15:45:00 ERROR (MainThread) [homeassistant.components.tts] Error on load tts: Wrong tts file format!"

The TTS is still played normally and I can hear it on speakers, just the error is recorded in the log. This only happens if the chosen entity for TTS is MPD. If I choose any other media entity for TTS to be played on (for example Google Nest Audio), it plays the same but without the error. Every other media (except TTS) and/or everything played directly from ympd webinterface gives no errors.  
Caching of TTS makes no difference - error occurs if the phrase is previously cached and also if it isn't. 

If it's of any help, here's also an example of a cached filename: 
64ed9aac086ada72b70fa0c716445977a592ee6a_en_-_google_translate.mp3
It's standard mp3, created by google translate (32kb/s). Also tried with other TTS services (Microsoft, voicerss) with 64kb/s and 160kb/s, but the result is the same. The "format" in the error obviously isn't related to mp3 coding.  

**To Reproduce**
 2022-01-13 15:45:00 ERROR (MainThread) [homeassistant.components.tts] Error on load tts: Wrong tts file format!

**Expected behavior**
No error in log, as the command is executed successfully and it can be heard on the speakers.

**Screenshots**

**System**

* Supervisor version: 2021.12.2
* Host system version: HA 2021.12.9, running Supervised in Docker 20.10.12 on Raspbian Bullseye

**Comment by AdmiralStipe** [comment] 2022-01-13 15:16
Additon from MPD log: 
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] mpd: applying... 
[fix-attrs.d] mpd: exited 0.
[fix-attrs.d] ympd: applying... 
[fix-attrs.d] ympd: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] setup-folders: executing... 
[16:13:48] INFO: Setup Folders
[cont-init.d] setup-folders: exited 0.
[cont-init.d] setup-settings: executing... 
[16:13:48] INFO: Setup settings
[16:13:48] INFO: Set media folder
[16:13:48] INFO: Set playlist folder
[cont-init.d] setup-settings: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:13:49] INFO: Start MPD
[16:13:50] INFO: Start ympd
MPD Connecting to 127.0.0.1:6600
MPD connected.
exception: CURL failed: The requested URL returned error: 404
exception: CURL failed: The requested URL returned error: 404
exception: CURL failed: The requested URL returned error: 404
exception: CURL failed: The requested URL returned error: 404
player: played "http://192.168.1.200:8123/api/tts_proxy/88db84f83dd687c33c9d181ef405809f2941c532_sl-si_-_microsoft.mp3"

CURL error also repeated four times.

**Comment by Poeschl** [comment] 2022-01-13 15:16
Uh, thanks for reporting. Will look into it, as always no eta.

**Comment by AdmiralStipe** [comment] 2022-01-13 15:28
Additional verbose log from MPD while executing a TTS command:

client: [1] process command "status"
client: [1] command returned 0
client: [1] process command "outputs"
client: [1] command returned 0
client: [2] process command "clear"
client: [2] command returned 0
client: [2] process command "add "http://192.168.1.200:8123/api/tts_proxy/c789e34604d38e878917e4f50d978b904be5bb63_sl-si_-_microsoft.mp3""
client: [2] command returned 0
client: [2] process command "play"
playlist: play 0:"http://192.168.1.200:8123/api/tts_proxy/c789e34604d38e878917e4f50d978b904be5bb63_sl-si_-_microsoft.mp3"
client: [2] command returned 0
client: [2] process command "status"
client: [2] command returned 0
decoder_thread: probing plugin mad
decoder: audio_format=24000:24:1, seekable=false
exception: OutputThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
client: [2] process command "currentsong"
client: [2] command returned 0
output: opened "Home Assistant Pulseaudio" (pulse) audio_format=24000:24:1
client: [2] process command "readpicture "http://192.168.1.200:8123/api/tts_proxy/c789e34604d38e878917e4f50d978b904be5bb63_sl-si_-_microsoft.mp3" "0""
client: [2] command returned 0
client: [2] process command "albumart "http://192.168.1.200:8123/api/tts_proxy/c789e34604d38e878917e4f50d978b904be5bb63_sl-si_-_microsoft.mp3" "0""
exception: CURL failed: The requested URL returned error: 404
exception: CURL failed: The requested URL returned error: 404
exception: CURL failed: The requested URL returned error: 404
exception: CURL failed: The requested URL returned error: 404
client: [2] command returned 3
client: [1] process command "status"
client: [1] command returned 0
client: [1] process command "outputs"
client: [1] command returned 0
client: [2] process command "idle "database""
client: [2] command returned 1
client: [1] process command "status"
client: [1] command returned 0
client: [1] process command "outputs"
client: [1] command returned 0
client: [1] process command "status"
client: [1] command returned 0
client: [1] process command "outputs"
client: [1] command returned 0
player: played "http://192.168.1.200:8123/api/tts_proxy/c789e34604d38e878917e4f50d978b904be5bb63_sl-si_-_microsoft.mp3"
playlist: stop
output: closed "Home Assistant Pulseaudio" (pulse)
client: [1] process command "status"
client: [1] command returned 0
client: [1] process command "outputs"
client: [1] command returned 0

**Comment by AdmiralStipe** [comment] 2022-01-13 16:52
Maybe related to [this issue](https://github.com/MusicPlayerDaemon/MPD/issues/1300)?

**Comment by AdmiralStipe** [comment] 2022-01-16 15:45
Not sure this helps, but I tried to additionally debug this, so I used telnet on mpd instance and tried two commands on the same file as above:

```
readpicture "http://192.168.1.200:8123/api/tts_proxy/78e406b7d7a28474dde229c6b8271244c634ad37_sl-si_-_microsoft.mp3" "0"
OK

albumart "http://192.168.1.200:8123/api/tts_proxy/78e406b7d7a28474dde229c6b8271244c634ad37_sl-si_-_microsoft.mp3" "0"
ACK [50@0] {albumart} No file exists

```
Not sure if I understand correctly, but seems to me, that albumart command can't read  the file from whatever reason (but that only happens when playing TTS  via "http:///IP...mp.3 file", with local files it doesn't seem to be a problem) and returns an error, which is then logged in HA (although no idea why it happens in four repetitions).

**Comment by AdmiralStipe** [comment] 2022-01-16 16:12
Not sure this helps, but I tried to additionally debug this, so I used telnet on mpd instance and tried two commands on the same file as above:

```
readpicture "http://192.168.1.200:8123/api/tts_proxy/78e406b7d7a28474dde229c6b8271244c634ad37_sl-si_-_microsoft.mp3" "0"
OK

albumart "http://192.168.1.200:8123/api/tts_proxy/78e406b7d7a28474dde229c6b8271244c634ad37_sl-si_-_microsoft.mp3" "0"
ACK [50@0] {albumart} No file exists

```
Not sure if I understand correctly, but seems to me, that albumart command can't find the file it expects (that would most likely be the JPEG/PNG/... in the directory, where the TTS file is, as stated [here](https://mpd.readthedocs.io/en/stable/protocol.html?highlight=albumart#the-music-database)) or simply can't understand, that this link is not a normal directory and is not browseable (we can only access one file with a direct link to it) and returns an error, which is then logged in HA (although no idea why it happens in four repetitions). 

So could the solution be to handle this error as it isn't an error or just disable the albumart when playing TTS or when playing any http file?

**Comment by AdmiralStipe** [comment] 2022-01-21 07:55
Found another related (basically the same) [issue](https://github.com/home-assistant/core/issues/47889), which also explains, why the error is repeated four times (it's checking for albumart file png, jpg, tiff and bmp in sequence, but can't access them).

**Comment by Poeschl** [comment] 2022-01-21 08:05
That could be a the reason. I wasn't able to look into it so far. Maybe there is an setting for mpd to skip the albumart requests.
This included in the default config should stop the 404s then

**Comment by AdmiralStipe** [comment] 2022-01-28 05:36
Not stale, just the author didn't have time to check it yet.

**Comment by Poeschl** [comment] 2022-01-28 16:27
Looked into mpd and the HA integration to solve this issue.
The errors are indeed caused by the picture requests, since the pure MPD implementation don't handle track images.
But the MPD integration in HA asks for one and tries all 4 options. The integration checks if its possible to get images from the MPD server and it seems that the used library for it just says yes in any case. :disappointed:

So unfortunately this issue can not be fixed in the context of the addon.
Inside the [HA integration the song thumbnail retrieval](https://github.com/home-assistant/core/blob/44572ff35455a27010c2eccd150417acaaa4aaad/homeassistant/components/mpd/media_player.py#L279) needs an other check (or maybe a config flag) or the [used mpd-library](https://github.com/Mic92/python-mpd2) needs to respond better to the compatibility check.

**Closed** 2022-02-01 21:06 UTC
Labels: bug, mpd
