### ISSUE TITLE
Cannot expose camera.rockrobo_map to HomeKit

### ISSUE THREAD

**Issue by Kugelfang666** [Poeschl/Hassio-Addons#162] opened 2021-01-03 18:52 UTC
**Which addon?**
ICantBelieveItsNotValetudo 2.5.0

**Describe the bug**
if I expose ```camera.rockrobo_map```the camera appears in HomeKit but without picture. If one clicks on the tile nothing is loaded. 
Other cameras, for instance my ```camera.octoprint_camera```, are working fine with the still image being updated regularly and a livestream being initiated upon clicking on the tile

**To Reproduce**
configuration.yaml

homekit:
  auto_start: true
  filter:
    include_entities:
      - camera.octoprint_camera
      - camera.rockrobo_map

**Expected behavior**
map should be accessible from within HomeKit as a camera

**Screenshots**

![Bildschirmfoto 2021-01-03 um 19 50 02](https://user-images.githubusercontent.com/3289654/103486269-e3919b80-4dfc-11eb-8374-57989b1670dc.png)

**System**

* Supervisor version: 2020.12.7
* Host system version: 2020.12.2

**Comment by Poeschl** [comment] 2021-01-03 18:55
This might be a duplicate of #89.?

**Comment by Kugelfang666** [comment] 2021-01-03 18:57
thans for pointing this out, yes it is a duplicate and can bel closed. Pitty tough that this feature is not available. Still thanks for looking into it!

**Closed** 2021-01-03 18:58 UTC
Labels: bug
