### ISSUE TITLE
Valetudo Mapper showing blue background -->NOT WANTED!

### ISSUE THREAD

**Issue by thundergreen** [Poeschl/Hassio-Addons#39] opened 2020-01-22 19:25 UTC
**Which addon?**

ValetudoMapper
**Describe the bug**

I Used ICantBeliveItsNotValetudo Addon before and I got a nice transparent map. Now with this version I get an ugly blue background. I cannot figure out how to deactivate this
**To Reproduce**

{
  "identifier": "rockrobo",
  "topicPrefix": "valetudo",
  "autoconfPrefix": "homeassistant",
  "broker_url": "mqtt://user:password@192.168.1.41",
  "caPath": "",
  "mapSettings": {
    "drawPath": true,
    "drawCharger": true,
    "drawRobot": true,
    "gradientBackground": false,
    "drawForbiddenZones": true,
    "drawVirtualWalls": true,
    "border": 2,
    "scale": 4
  },
  "mapDataTopic": "valetudo/rockrobo/map_data",
  "minMillisecondsBetweenMapUpdates": 10000,
  "publishMapImage": true,
  "publishMapData": true
}
**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/13320319/72926951-959f9700-3d55-11ea-8dd5-46d71d4d3d71.png)

**Comment by Poeschl** [comment] 2020-01-22 20:29
Duplicate of #38

I understand your problem, since I'm not using the valetudo-mapper myself I can't help you with that.

Also note valetudo-mapper ≠ ICantBeliveItsNotValetudo.
As far as I see this it's a problem of the mapper itself and not the addon. So please go to the mapper itself to get support. 

Maybe @apoc4lyps has an idea.

**Comment by apoc4lyps** [comment] 2020-01-22 20:40
Currently valetudo-mapper does not provide this feature. you can raise an issue / pull request to fulfill your requirements.
hint: https://github.com/rand256/valetudo-mapper/blob/master/lib/Tools.js#L45

**Closed** 2020-01-22 20:40 UTC
Labels: bug, wontfix
